version: '3.8'
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 6582:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s
volumes:
  yacht:
networks:
  default:
    external:
      name: pacman
