version: '3.8'
services:
  openhab:
    image: "openhab/openhab:milestone-alpine"
    container_name: Openhab
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Copenhagen"
     healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s
networks:
  default:
    external:
      name: pacman

