version: '3.8'
services:
  restserver:
    image: eikek0/sharry:nightly
    container_name: Sharry
    command: /opt/sharry.conf
    ports:
      - "9090:9090"
    volumes:
      - ./sharry.conf:/opt/sharry.conf
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sharry_db
      - POSTGRES_PASSWORD=D87b527ShArRy928
      - POSTGRES_DB=db_sharry
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s
volumes:
  postgres_data:
networks:
  default:
    external:
      name: pacman
