pageInfo:
  title: Dashy by Fabse Inc.
  description: My awesome dashboard with free puns :)
  footerText: If curious about the source code, please check fabsepi.space
  logo: https://i.ibb.co/yhbt6CY/dashy.png
  navLinks:
  - title: Home
    path: /
  - title: I'm bored
    path: https://theuselessweb.com/
appConfig:
  statusCheck: true
  enableFontAwesome: true
  theme: colorful
  enableErrorReporting: true
sections:
- name: File management
  displayData:
    cols: 1
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: Filebrowser
    description: Accessing all synchronized files
    icon: generative
    url: https://filebrowser.fabsemanpi.space
    target: sametab
  - title: Photoprism
    description: Photo and video gallery
    icon: generative
    url: https://photoprism.fabsemanpi.space
    target: sametab
  - title: Synthing_RPI4
    description: Synchronizing files adjust all platforms
    icon: generative
    url: https://syncthing_rpi4.fabsemanpi.space
    target: sametab
  - title: Syncthing_ARTIX
    description: Laptop interface regarding synchronizing
    icon: generative
    url: https://syncthing_artix.fabsemanpi.space
    target: sametab
- name: Productivity
  displayData:
    cols: 1
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: Etherpad
    description: Open-source online editor
    icon: generative
    url: https://etherpad.fabsemanpi.space
    target: sametab
  - title: Hedgedoc
    description: Open-source markdown editor
    icon: generative
    url: https://hedgedoc.fabsemanpi.space
    target: sametab
  - title: Docspell
    description: Document organizer
    icon: generative
    url: https://docspell.fabsemanpi.space
    target: sametab
  - title: Vikunja
    description: South American camelids
    icon: generative
    url: https://vikunja.fabsemanpi.space
    target: sametab
- name: Media and file transfers
  displayData:
    cols: 1
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: Navidrome
    description: Music server and collector
    icon: generative
    url: https://navidrome.fabsemanpi.space
    target: sametab
  - title: Sharry
    description: File transfers with link-sharing
    icon: generative
    url: https://sharry.fabsemanpi.space
    target: sametab
  - title: Exatorrent
    description: Beautiful torrent client
    icon: generative
    url: https://exatorrent.fabsemanpi.space
    target: sametab
- name: Automation
  displayData:
    cols: 1
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: OpenHAB
    description: Home-automation
    icon: generative
    url: https://openhab.fabsemanpi.space
    target: sametab
  - title: Leon-AI
    description: Open-source AI
    icon: generative
    url: https://leon.fabsemanpi.space
    target: sametab
- name: System management
  displayData:
    cols: 2
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: Nginx proxy manager
    description: Managing reverse-proxies
    icon: generative
    url: https://nginx.fabsemanpi.space
    target: sametab
  - title: Netdata
    description: Frontend for system management
    icon: generative
    url: https://netdata.fabsemanpi.space
    target: sametab
  - title: Uptime-kuma
    description: Monitoring status of my services
    icon: generative
    url: https://uptime.fabsemanpi.space
    target: sametab
  - title: Yacht
    description: A sailing or power vessel used for pleasure
    icon: generative
    url: https://yacht.fabsemanpi.space
    target: sametab
  - title: Grafana
    description: Open-source data visualiser with modularity
    icon: generative
    url: https://grafana.fabsemanpi.space
    target: sametab
  - title: Prometheus
    description: Open-source database indexer with monitoring
    icon: generative
    url: https://prometheus.fabsemanpi.space
    target: sametab
- name: External services
  displayData:
    cols: 2
    rows: 1
    sortBy: random
    collapsed: false
    itemSize: large
  items:
  - title: Definely not a Rick-roll
    description: I really mean it
    icon: generative
    url: https://fabsepi.space
    target: newtab
  - title: Xkcd
    description: Best webcomic since Donald Duck
    icon: generative
    url: https://xkcd.com
    target: newtab
  - title: Librespeed
    description: Speedtest with quote no bullshit
    icon: generative
    url: https://https://librespeed.org/
    target: newtab
