version: '3.8'
services:
  grafana:
    ports:
      - '6625:3000'
    container_name: Grafana
    image: grafana/grafana:main
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
networks:
  default:
    external:
      name: pacman
