version: "3.8"
services:
  watchtower:
    container_name: Watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/Copenhagen"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s
networks:
  default:
    external:
      name: pacman
